#ifndef JSON_H
#define JSON_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Minimal, self-contained JSON reader - not a general-purpose library,
 * just enough to parse graph_config.c's fixed schema (objects, arrays,
 * strings, numbers, bools) without pulling in an external dependency
 * (cJSON or similar) into a project family that's so far vendored
 * everything it needs rather than adding a new third-party library. No
 * writer - graph files are hand-authored (v1) or written by the future
 * web UI's own JS JSON.stringify() (Phase 3), never generated by this
 * binary. */

enum json_type {
	JSON_NULL,
	JSON_BOOL,
	JSON_NUMBER,
	JSON_STRING,
	JSON_OBJECT,
	JSON_ARRAY,
};

struct json_value;

/* Parses text in place (text must stay alive as long as the returned
 * tree is used - strings point into it, no copying). Returns NULL on a
 * syntax error, with a human-readable message written into errbuf. The
 * returned tree is heap-allocated; free with json_free(). */
struct json_value *json_parse(char *text, char *errbuf, size_t errbuf_len);
void json_free(struct json_value *v);

enum json_type json_get_type(const struct json_value *v);

/* NULL if v isn't an object or the key isn't present. */
const struct json_value *json_object_get(const struct json_value *v, const char *key);

/* 0 if v isn't an array. */
size_t json_array_size(const struct json_value *v);
/* NULL if v isn't an array or idx is out of range. */
const struct json_value *json_array_get(const struct json_value *v, size_t idx);

/* Every json_as_*() returns default_val if v is NULL or the wrong type -
 * callers use this the same way query_get_uint()'s callers already
 * treat "not present" and "present but wrong shape" as one case: fall
 * back, don't crash. graph_config.c's own schema validation is what
 * turns a truly required-but-missing field into a startup error;
 * these accessors alone never do. */
bool json_as_bool(const struct json_value *v, bool default_val);
double json_as_number(const struct json_value *v, double default_val);
const char *json_as_string(const struct json_value *v, const char *default_val);

#endif
